//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSIGNED
    {
        public string Student { get; set; }
        public string Module { get; set; }
        public Nullable<int> DateIssued { get; set; }
    
        public virtual MODULE MODULE1 { get; set; }
        public virtual STUDENT STUDENT1 { get; set; }
    }
}
