//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DGdbEntities1 : DbContext
    {
        public DGdbEntities1()
            : base("name=DGdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASSIGNED> ASSIGNEDs { get; set; }
        public virtual DbSet<MODULE> MODULEs { get; set; }
        public virtual DbSet<STUDENT> STUDENTs { get; set; }
    }
}
